#!/bin/bash

needle=$1
pick=$2

dirs_raw=($(locate --regexp "/$needle\$"))
dirs=()
j=0
for i in $(seq 0 $((${#dirs_raw[@]} - 1)))
do
    if [ -d "${dirs_raw[$i]}" ]
    then
        dirs[$j]=${dirs_raw[$i]}
        j=$(($j + 1))
    fi
done
dirlen=${#dirs[@]}
if [ "$dirlen" = 0 ]
then
    exit 1
fi
if [ "$dirlen" -eq 1 ]
then
    echo ${dirs[0]}
    exit 0
fi
if [ $pick ]
then
    echo ${dirs[$pick]}
    exit 0
fi
for i in $(seq 0 $(($dirlen - 1)))
do
    echo "$i: ${dirs[$i]}"
done
exit 2
